CREATE TABLE planned_route (
    id                UUID PRIMARY KEY,
    name              VARCHAR(255),
    profile           VARCHAR(255) NOT NULL,
    origin_lat        DOUBLE PRECISION NOT NULL,
    origin_lon        DOUBLE PRECISION NOT NULL,
    origin_label      VARCHAR(255),
    destination_lat   DOUBLE PRECISION NOT NULL,
    destination_lon   DOUBLE PRECISION NOT NULL,
    destination_label VARCHAR(255),
    distance_meters   BIGINT NOT NULL,
    duration_seconds  BIGINT NOT NULL,
    geometry          TEXT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_planned_route_created_at ON planned_route (created_at);

CREATE TABLE planned_route_stop (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planned_route_id UUID NOT NULL REFERENCES planned_route (id) ON DELETE CASCADE,
    lat              DOUBLE PRECISION NOT NULL,
    lon              DOUBLE PRECISION NOT NULL,
    label            VARCHAR(255),
    stop_order       INTEGER NOT NULL
);

CREATE INDEX idx_planned_route_stop_route ON planned_route_stop (planned_route_id);
