CREATE TABLE toll_plaza (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concessionaria VARCHAR(255),
    nome           VARCHAR(255),
    ano_pnv_snv    INTEGER,
    rodovia        VARCHAR(64)  NOT NULL,
    uf             VARCHAR(2),
    km_m           NUMERIC(12,3) NOT NULL,
    municipio      VARCHAR(255),
    tipo_pista     VARCHAR(64),
    sentido        VARCHAR(64)  NOT NULL,
    latitude       DOUBLE PRECISION NOT NULL,
    longitude      DOUBLE PRECISION NOT NULL,
    active         BOOLEAN NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX ux_toll_plaza_natural_key ON toll_plaza (rodovia, km_m, sentido);
CREATE INDEX idx_toll_plaza_lat_lon ON toll_plaza (latitude, longitude);
