CREATE TABLE planned_route_toll (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planned_route_id UUID NOT NULL REFERENCES planned_route (id) ON DELETE CASCADE,
    nome             VARCHAR(255),
    concessionaria   VARCHAR(255),
    rodovia          VARCHAR(64)  NOT NULL,
    uf               VARCHAR(2),
    km_m             NUMERIC(12,3) NOT NULL,
    sentido          VARCHAR(64)  NOT NULL,
    latitude         DOUBLE PRECISION NOT NULL,
    longitude        DOUBLE PRECISION NOT NULL,
    match_order      INTEGER NOT NULL
);

CREATE INDEX idx_planned_route_toll_route ON planned_route_toll (planned_route_id);
